// <auto-generated />
using System;
using KSociety.Example.Infra.Transfer.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSociety.Example.Infra.Transfer.Sqlite.Migrations
{
    [DbContext(typeof(SqliteExampleContext))]
    partial class SqliteExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("KSociety.Example.Domain.Entity.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Title", "AuthorName")
                        .IsUnique();

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("85ee13a1-4584-458f-9ef1-5c0101e54264"),
                            AuthorName = "1",
                            Title = "1"
                        },
                        new
                        {
                            Id = new Guid("93a2dfbe-8bf0-48c4-8210-1991bc95070f"),
                            AuthorName = "2",
                            Title = "2"
                        },
                        new
                        {
                            Id = new Guid("7d9a0b7d-dab2-4d69-bee8-a4a68a3e12ad"),
                            AuthorName = "3",
                            Title = "3"
                        },
                        new
                        {
                            Id = new Guid("701fc68d-4aef-4ef3-b074-05e1ad021b2c"),
                            AuthorName = "4",
                            Title = "4"
                        },
                        new
                        {
                            Id = new Guid("0d9ddd0d-eda7-4347-b954-e521da8f02a2"),
                            AuthorName = "5",
                            Title = "5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
